version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  web:
    image: python:3.8
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    working_dir: /code
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis